config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get '/secret', to: 'pages#secret', as: :secret
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # database_authenticatable – Users will be able to authenticate with a login and password that are stored in the database.
  # (password is stored in a form of a digest).
  # registerable – Users will be able to register, update, and destroy their profiles.
  # recoverable – Provides mechanism to reset forgotten passwords.
  # rememberable – Enables “remember me” functionality that involves cookies.
  # trackable – Tracks sign in count, timestamps, and IP address.
  # validatable – Validates e-mail and password (custom validators can be used).

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :zxcvbnable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later # Means that the sending will be queued up
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Devise In Depth
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .nav.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          = link_to 'Devise demo', root_path, class: 'navbar-brand'
        #navbar
          ul.nav.navbar-nav
            li = link_to 'Home', root_path
            - if user_signed_in?
              li = link_to 'Secret', secret_path
          ul.nav.navbar-nav.pull-right
            - if user_signed_in?
              li.dropdown
                a.dropdown-toggle[aria-expanded="false" role="button" data-toggle="dropdown" href="#"]
                  = current_user.name
                  span.caret
                ul.dropdown-menu[role="menu"]
                  li = link_to 'Profile', edit_user_registration_path
                  li = link_to 'Log out', destroy_user_session_path, method: :delete
            - else
              li = link_to 'Sign in', new_user_session_path
              li = link_to 'Sign up', new_user_registration_path
    - flash.each do |key, value|
      div class="alert alert-#{key}"
        .container
          = value
    = yield :top_content
    .container
      h1 = yield :header
      = yield

app/views/pages/index.html.slim
- content_for :top_content
  .jumbotron
    .container
      h1 Welcome!
      p Register to get started.
      p = link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg'

app/views/pages/secret.html.slim
- header 'Secret!'